#!/usr/bin/env bash
# CPU-host calibration orchestration: run every gate that depends on the
# generated production corpus, in order. Each step is idempotent against
# its own output file: re-running the script after a partial run will
# pick up where it left off.
#
# Required env (loaded from /root/cortex/.env via run-with-env.py):
#   HF_ACCESS_TOKEN  — for huggingface_hub when models are cold-cached
#   BASE_RPC_URL     — for the optional read-only mainnet binding probe
#
# Required artifact (generated by the calibration corpus run):
#   /var/lib/coretex/corpus-epoch-0-calibration.json
#
# Outputs:
#   /var/lib/coretex/reports/corpus-validation.json
#   /var/lib/coretex/reports/determinism-host-{a,b,c}.json
#   /var/lib/coretex/reports/determinism-aggregate.json
#   /etc/coretex/bundle-profile.json
#   /etc/coretex/bundle-manifest.json
#   /var/lib/coretex/reports/phase13-real.log
#   /var/lib/coretex/reports/final-launch-summary.md
set -euo pipefail

CORPUS=/var/lib/coretex/corpus-epoch-0-calibration.json
TEMPLATE_BUNDLE=/etc/coretex/template-bundle.json
DETERMINISM_FIXTURE=/var/lib/coretex/determinism-1k-pairs.json
REPORTS=/var/lib/coretex/reports
PROFILE=/etc/coretex/bundle-profile.json
BUNDLE=/etc/coretex/bundle-manifest.json

mkdir -p "$REPORTS"

if [ ! -f "$CORPUS" ]; then
  echo "orchestrate: corpus not present at $CORPUS — run the calibration corpus first" >&2
  exit 1
fi

# Common env for all subprocess-bearing steps. Loaded once and exported.
export CORETEX_BIENCODER_PYTHON=/root/cortex/.venv/bin/python
export CORETEX_RERANKER_PYTHON=/root/cortex/.venv/bin/python
export CORTEX_LOCAL_MODEL_CACHE=/var/lib/coretex/model-cache
export HF_HUB_CACHE=/var/lib/coretex/model-cache
export HF_HUB_OFFLINE=1
export BIENCODER_NUM_THREADS=16
export BIENCODER_INNER_BATCH=64
export RERANKER_NUM_THREADS=16
export RERANKER_INNER_BATCH=8
export CORETEX_BIENCODER=pinned
export CORETEX_BIENCODER_MODE=streaming
export CORETEX_RERANKER=qwen3
export CORETEX_RERANKER_MODE=streaming
export CORETEX_RERANKER_PRODUCTION=1
export CORTEX_REAL_EVAL=1

step() { echo; echo "==== $* ===="; }

step "1/7 validate corpus shape"
node /root/cortex/scripts/validate-retrieval-corpus.mjs \
  --corpus "$CORPUS" \
  --min-events 100 --min-per-family 1 --min-hard-negatives 3 \
  --out "$REPORTS/corpus-validation.json"
node -e "const r=JSON.parse(require('fs').readFileSync('$REPORTS/corpus-validation.json','utf8')); if((r.errors||[]).length){console.error(r.errors); process.exit(1);} console.log('corpus errors=0 events='+r.eventCount+' families='+JSON.stringify(r.familyCounts));"

step "2/7 build determinism fixture"
if [ ! -f "$DETERMINISM_FIXTURE" ]; then
  node /root/cortex/scripts/build-determinism-fixture.mjs --corpus "$CORPUS" --out "$DETERMINISM_FIXTURE" --max-pairs 200
else
  echo "(reusing existing fixture)"
fi

step "3/7 determinism check on this host (3 logical hosts via repeated runs)"
for HOST in host_a host_b host_c; do
  REPORT="$REPORTS/determinism-host-$HOST.json"
  if [ ! -f "$REPORT" ]; then
    HOSTNAME="$HOST" node /root/cortex/scripts/determinism-check.mjs \
      --bundle-manifest "$TEMPLATE_BUNDLE" \
      --pairs "$DETERMINISM_FIXTURE" \
      --hosts "$HOST" \
      --max-tolerance-ppm 250 \
      --report "$REPORT"
  else
    echo "(reusing $REPORT)"
  fi
done

step "4/7 aggregate determinism"
node /root/cortex/scripts/aggregate-determinism.mjs \
  --reports "$REPORTS/determinism-host-*.json" \
  --max-tolerance-ppm 250 \
  --out "$REPORTS/determinism-aggregate.json"

step "5/7 calibrate bundle profile"
node /root/cortex/scripts/calibrate.mjs \
  --bundle-manifest "$TEMPLATE_BUNDLE" \
  --calibration-corpus "$CORPUS" \
  --determinism-aggregate "$REPORTS/determinism-aggregate.json" \
  --out "$PROFILE"

step "6/7 build final bundle manifest"
node /root/cortex/scripts/build-coretex-bundle.mjs \
  --repo-root /root/cortex \
  --corpus "$CORPUS" \
  --profile "$PROFILE" \
  --out "$BUNDLE"

step "7/7 Phase 13 e2e against real models + final bundle + calibration corpus"
ITERATIONS=${ITERATIONS:-5} \
CORETEX_BUNDLE_MANIFEST="$BUNDLE" \
CORETEX_CORPUS="$CORPUS" \
node /root/cortex/test/e2e/phase-13/run.mjs 2>&1 | tee "$REPORTS/phase13-real.log"

step "DONE — writing summary"
node -e "
const fs=require('fs');
const corpus=JSON.parse(fs.readFileSync('$CORPUS','utf8'));
const profile=JSON.parse(fs.readFileSync('$PROFILE','utf8'));
const bundle=JSON.parse(fs.readFileSync('$BUNDLE','utf8'));
const valid=JSON.parse(fs.readFileSync('$REPORTS/corpus-validation.json','utf8'));
const detAgg=JSON.parse(fs.readFileSync('$REPORTS/determinism-aggregate.json','utf8'));
const out = [
  '# CoreTex CPU calibration summary',
  '',
  'Generated: ' + new Date().toISOString(),
  '',
  '## corpus',
  '- file: $CORPUS',
  '- events: ' + corpus.events.length,
  '- corpusRoot: ' + corpus.corpusRoot,
  '- biEncoder: ' + corpus.biEncoder.modelId + '@' + corpus.biEncoder.revision,
  '- labelingModel: ' + corpus.labelingModel.modelId + '@' + corpus.labelingModel.revision,
  '- families: ' + JSON.stringify(valid.familyCounts),
  '- splits: ' + JSON.stringify(valid.splitCounts),
  '',
  '## determinism aggregate',
  '- max tolerance ppm: ' + (detAgg.maxTolerancePpm ?? 'n/a'),
  '- p50 ppm: ' + (detAgg.p50PpmDiff ?? 'n/a'),
  '- p90 ppm: ' + (detAgg.p90PpmDiff ?? 'n/a'),
  '- p99 ppm: ' + (detAgg.p99PpmDiff ?? 'n/a'),
  '- pass: ' + (detAgg.pass ?? false),
  '',
  '## bundle',
  '- bundleHash: ' + bundle.bundleHash,
  '- coreVersionHash: ' + bundle.bundleHash,
  '- biEncoder: ' + bundle.model.biEncoder.modelId + '@' + bundle.model.biEncoder.revision,
  '- reranker: ' + bundle.model.reranker.modelId + '@' + bundle.model.reranker.revision,
  '- labeling reranker: ' + bundle.model.labelingReranker.modelId + '@' + bundle.model.labelingReranker.revision,
  '- corpusRoot pinned: ' + bundle.corpus.root,
  '- composite weights: ' + JSON.stringify(bundle.evaluator.profile.compositeWeights),
  '- patch acceptance floors: ' + JSON.stringify(bundle.evaluator.profile.patchAcceptanceFloors),
  '- replayTolerancePpm: ' + bundle.evaluator.profile.replayTolerancePpm,
  '',
  '## phase 13',
  '- log: $REPORTS/phase13-real.log',
  '',
].join('\\n');
fs.writeFileSync('$REPORTS/final-launch-summary.md', out);
console.log('summary at $REPORTS/final-launch-summary.md');
"
